name: Build, Push Docker Image & Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      IMAGE_NAME: strapi-app
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/strapi-app:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE ./my-strapi-app

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_IMAGE

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./task8

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./task8

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./task8
